name: Deploy to EC2

on:
  push:
    branches:
      - main # deploy only when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2-key.pem
          chmod 400 ec2-key.pem

      - name: Deploy to EC2 with rsync
        run: |
          rsync -avz --delete \
            --exclude 'node_modules' \
            --exclude '.git' \
            --exclude '.gitignore' \
            --exclude '*.log' \
            --exclude '.vscode' \
            --exclude 'coverage' \
            -e "ssh -i ec2-key.pem -o StrictHostKeyChecking=no" \
            ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app

      - name: Install dependencies & restart app
        run: |
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            cd /home/ubuntu/app &&
            npm install --production &&
            pm2 startOrReload ecosystem.config.js
          "
